import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { AppLayout } from '@/components/layout/AppLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles, Mail, Key, UserPlus, ExternalLink, RefreshCw } from 'lucide-react';
import { madConfig } from '@/lib/config';
import { generateRandomString, formatEmail, createDcLoginLink, tryOpenProtocol } from '@/lib/account-utils';
import { QRCodeDisplay } from '@/components/QRCodeDisplay';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';
import { api } from '@/lib/api-client';
import type { Account } from '@shared/types';
type FlowState = 'idle' | 'generating' | 'success' | 'error';
export function HomePage() {
  const [state, setState] = useState<FlowState>('idle');
  const [creds, setCreds] = useState<{ email: string; pass: string } | null>(null);
  const hasAutoGenerated = useRef(false);
  const stateRef = useRef<FlowState>();
  useEffect(() => {
    stateRef.current = state;
  }, [state]);
  const handleCreateAccount = useCallback(async () => {
    if (stateRef.current === 'generating') return;
    setState('generating');
    try {
      if (madConfig.jitEnabled) {
        await new Promise(r => setTimeout(r, 600));
        const user = generateRandomString(8);
        const pass = generateRandomString(12);
        const email = formatEmail(user, madConfig.mailDomain);
        setCreds({ email, pass });
        setState('success');
        toast.success('حساب با موفقیت ایجاد شد');
      } else {
        const response = await api<Account>('/new', {
          method: 'POST',
          body: JSON.stringify({ name: 'کاربر جدید' })
        });
        setCreds({ email: response.email, pass: response.password });
        setState('success');
        toast.success('حساب از سرور دریافت شد');
      }
    } catch (error) {
      console.error(error);
      setState('error');
      toast.error('خطا در ایجاد ��ساب کاربری. لطفاً دوباره تلاش کنید.');
    }
  }, []);
  useEffect(() => {
    if (madConfig.registrationOpen && madConfig.jitEnabled && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleCreateAccount();
    }
  }, [handleCreateAccount]);
  const loginLink = useMemo(() => {
    if (!creds) return '';
    return createDcLoginLink({
      email: creds.email,
      password: creds.pass,
      ssl: !madConfig.turnOffTLS
    });
  }, [creds]);
  const qrCodeSection = useMemo(() => (
    <QRCodeDisplay
      value={loginLink}
      label="این کد را با DeltaChat اسکن کنید"
    />
  ), [loginLink]);
  const handleOpenDeltaChat = async () => {
    const success = await tryOpenProtocol(loginLink);
    if (!success) {
      toast.info('DeltaChat یافت نشد. لطفاً ابتدا برنامه ��ا نصب کنید.');
    }
  };
  return (
    <AppLayout>
      <div className="flex flex-col items-center gap-8">
        <header className="text-center space-y-4">
          <motion.div
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="inline-flex items-center justify-center p-3 rounded-2xl bg-primary/10 text-primary mb-2"
          >
            <Sparkles className="w-8 h-8" />
          </motion.div>
          <h1 className="text-4xl font-black tracking-tight text-foreground sm:text-5xl">
            سروی�� پیام‌رسان <span className="text-primary">MadMail</span>
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto px-4">
            یک سرور DeltaChat امن و خصوصی برای ارتباطات آزاد شما. همین ��الا حساب کاربری خود را بسازید.
          </p>
        </header>
        <AnimatePresence mode="wait">
          {state === 'idle' || state === 'error' ? (
            <motion.div
              key="idle"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-md px-4"
            >
              <Card className="border-2 shadow-xl overflow-hidden">
                <CardHeader className="pb-4">
                  <CardTitle>ایجاد حساب جدید</CardTitle>
                  <CardDescription>
                    با کلیک روی دکمه زیر، یک آدرس ایمیل اختصاصی برای استفاده در DeltaChat دریافت کنید.
                  </CardDescription>
                </CardHeader>
                <CardFooter>
                  <Button
                    className="w-full h-14 text-lg font-bold gap-3 shadow-lg hover:shadow-primary/40 transition-all bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white border-none"
                    onClick={handleCreateAccount}
                    disabled={!madConfig.registrationOpen}
                  >
                    <UserPlus className="w-5 h-5" />
                    ساخت اکانت در {madConfig.mailDomain}
                  </Button>
                </CardFooter>
                {state === 'error' && (
                  <div className="px-6 pb-4 text-center">
                    <button onClick={() => setState('idle')} className="text-xs text-muted-foreground hover:text-primary underline">
                      تلاش مجدد
                    </button>
                  </div>
                )}
              </Card>
            </motion.div>
          ) : null}
          {state === 'generating' && (
            <motion.div
              key="generating"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center gap-6 py-12"
            >
              <div className="relative">
                <RefreshCw className="w-16 h-16 text-primary animate-spin" />
                <div className="absolute inset-0 flex items-center justify-center">
                   <div className="w-4 h-4 bg-primary rounded-full animate-pulse" />
                </div>
              </div>
              <p className="text-xl font-bold text-primary animate-pulse">در حال پیکربندی ایمیل شما...</p>
            </motion.div>
          )}
          {state === 'success' && creds && (
            <motion.div
              key="success"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="w-full max-w-3xl grid md:grid-cols-2 gap-8 items-start px-4"
            >
              {qrCodeSection}
              <div className="space-y-6">
                <Card className="border-primary/20 bg-primary/5 shadow-inner">
                  <CardContent className="p-[15px] rounded-[8px] bg-black/5 space-y-5">
                    <div className="flex items-center gap-4">
                      <div className="p-2.5 bg-background rounded-xl border shadow-sm shrink-0">
                        <Mail className="w-6 h-6 text-primary" />
                      </div>
                      <div className="flex-1 overflow-hidden">
                        <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-widest mb-0.5">آدرس ایمیل</p>
                        <p className="font-mono text-sm md:text-base truncate select-all" dir="ltr">{creds.email}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="p-2.5 bg-background rounded-xl border shadow-sm shrink-0">
                        <Key className="w-6 h-6 text-primary" />
                      </div>
                      <div className="flex-1 overflow-hidden">
                        <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-widest mb-0.5">رمز عبور</p>
                        <p className="font-mono text-sm md:text-base truncate select-all" dir="ltr">{creds.pass}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <div className="flex flex-col gap-3">
                  <Button className="h-14 text-lg gap-3 shadow-xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white border-none" onClick={handleOpenDeltaChat}>
                    <ExternalLink className="w-5 h-5" />
                    ورود مستقیم به DeltaChat
                  </Button>
                  <Button variant="outline" className="h-12 border-2" onClick={handleCreateAccount}>
                    ساخت حساب کاربری دیگر
                  </Button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </AppLayout>
  );
}